### ISSUE TITLE
`make_shared_secret` fails with ZMQError: Not supported

### ISSUE THREAD

**Issue by dihm** [chrisjbillington/zprocess#19]
First reported in labscript-suite/labscript-suite#83

Can reproduce this on windows using the conda provided zeromq==4.3.5. Fundamental problem is the call to `zmq.curve_keypair()`.

```python
>>> import zmq
>>> zmq.curve_keypair()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zmq/backend/cython/utils.pyx", line 60, in zmq.backend.cython.utils.curve_keypair
  File "C:\Users\naqsL\miniconda3\envs\labscript\Lib\site-packages\zmq\error.py", line 149, in _check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Not supported
```

Issue may be wider, but I suspect there is an issue with the conda build recipe. Not 100% sure where to even report it...

**Comment by chrisjbillington** [comment]
Gah, conda failing to build their packages with the cryptography stuff set up properly is such a perennial problem. Usually it just results in slow crypto, now apparently no crypto? I'll look into it to figure out if it's conda's fault or not and report a bug - I've reported them before so I'll figure out where.

**Comment by dihm** [comment]
I did submit something [here](https://github.com/ContinuumIO/anaconda-issues/issues/13339) which I think is to the right place. Guess we'll find out.

**Comment by dihm** [comment]
Annoyingly, this appears to still be an issue. I'm not sure if there is even a half-reasonable way for us to specify that 4.3.5 needs to come from conda-forge in the requirements, or just block 4.3.5 from installing on windows, or some other viable work-around.
